### PR TITLE
About page initial front end implementation

### PR DESCRIPTION
**Pull request by juliaelman**
Adding styling/layout for the about page implementation, refs #76. Some other design decisions made: 

- Remove numbers on questions/answers
- Change disclaimer background to dark purple and text to white.

screen shot 2015-05-13 at 3 38 38 pm

### CODE REVIEW

**Comment by konklone** [comment]
Looks beautiful. :+1: I've assigned myself and will add some copy (doesn't have to be final) to get this started, then merge.

**Comment by juliaelman** [comment]
Right on. Thanks @konklone!

**Comment by konklone** [comment]
I've added some starting text, and wired up the links. @jtexnl, I assume you have other copy and stuff you'll want to integrate or replace this stuff with, so maybe let's sync up on that soon?

**Comment by juliaelman** [comment]
@konklone perfect! :rocket:

**Pull request merged**
